title: Xiletrade
description: Price checker and helper tool for Path Of Exile games
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  repository_name: Xiletrade
  owner_name: maxensas
  is_project_page: true
  owner_url: https://github.com/maxensas/
  repository_url: https://github.com/maxensas/xiletrade
  latest_url: https://github.com/maxensas/xiletrade/releases/latest/
  zip_url: https://github.com/maxensas/xiletrade/releases/download/1.10.5/Xiletrade_win-x64.7z
  download_url: https://github.com/maxensas/xiletrade/releases/download/
  archive_file: Xiletrade_win-x64.7z
  latest_version: 1.10.6